### ISSUE TITLE
impossible to open tabular editor from Power Bi Desktop

### ISSUE THREAD

**Issue by PalombieChamonix** [TabularEditor/TabularEditor3#229]
Opening tabulard editor from power bi desktop fails.

From Power BI Desktop, I'm trying to use Tabular editor 3 from external tools.
Tabular Editor opens, dipslaying the warning message ('Power Bi Desktop Warningand finally closes.
I've tried to open first tabular editor and then to load model from Power Bi instance : same bug. 

 - Tabular Editor version : 3.1.7918.37005

Best regards

**Comment by otykier** [comment]
Hi @PalombieChamonix
To help us identify this issue could you launch the Windows Event Viewer and look for any .NET Runtime Error events within **Windows Logs > Application** around the time where Tabular Editor 3 closes itself. Please share the details of any such errors (see screenshot below for reference):

![image](https://user-images.githubusercontent.com/8976200/135101179-69d6692c-c55b-4ccb-82cb-34c3f30c4a23.png)

**Comment by PalombieChamonix** [comment]
Hi Daniel,

Here are the windows logs :
Nom de l'application défaillante TabularEditor3.exe, version : 3.1.7918.37005, horodatage : 0x61350d7c
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.1202, horodatage : 0xc9db1934
Code d'exception : 0xe0434352
Décalage d'erreur : 0x0000000000034f99
ID du processus défaillant : 0x7814
Heure de début de l'application défaillante : 0x01d7b46d7c6e4222
Chemin d'accès de l'application défaillante : C:\Program Files\Tabular Editor 3\TabularEditor3.exe
Chemin d'accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : f1d3113f-accc-4135-a6a7-d321dbed0196
Nom complet du package défaillant :
ID de l'application relative au package défaillant :

Application: TabularEditor3.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.ThrowHelper.ThrowArgumentNullException(System.ExceptionArgument)
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Dax.Analyzer.Ast.CrossFilterDirection, Dax.Analyzer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Insert(System.__Canon, Dax.Analyzer.Ast.CrossFilterDirection, Boolean)
   at Dax.Analyzer.FilterContext.Merge(Dax.Analyzer.FilterContext, System.Collections.Generic.IEnumerable`1<Dax.Analyzer.Ast.DaxBaseNode>)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.PushModifiedFilterContext(System.Collections.Generic.IEnumerable`1<Dax.Analyzer.Ast.DaxBaseNode>)
   at Dax.Analyzer.Ast.FunctionNode.AcceptCalculate()
   at Dax.Analyzer.Ast.FunctionNode.Accept(Dax.Analyzer.Ast.Visitor.DaxVisitor, FunctionExprContext)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.__Canon)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitChildren(Antlr4.Runtime.Tree.IRuleNode)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(Antlr4.Runtime.Tree.IParseTree)
   at Dax.Analyzer.Ast.VariableDeclarationNode.AcceptExpression()
   at Dax.Analyzer.Ast.VariableDeclarationBlockNode.Accept(Dax.Analyzer.Ast.Visitor.DaxVisitor, VarDeclarationBlockExprContext)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.__Canon)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(Antlr4.Runtime.Tree.IParseTree)
   at Dax.Analyzer.Ast.FunctionNode.VisitArg(Int32, Boolean, Boolean)
   at Dax.Analyzer.Ast.FunctionNode+IfAcceptor.Accept(Dax.Analyzer.Ast.FunctionNode)
   at Dax.Analyzer.Ast.FunctionNode.Accept(Dax.Analyzer.Ast.Visitor.DaxVisitor, FunctionExprContext)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.__Canon)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitChildren(Antlr4.Runtime.Tree.IRuleNode)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(Antlr4.Runtime.Tree.IParseTree)
   at Dax.Analyzer.Ast.FunctionNode.VisitArg(Int32, Boolean, Boolean)
   at Dax.Analyzer.Ast.FunctionNode+IfAcceptor.Accept(Dax.Analyzer.Ast.FunctionNode)
   at Dax.Analyzer.Ast.FunctionNode.Accept(Dax.Analyzer.Ast.Visitor.DaxVisitor, FunctionExprContext)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.CreateAndVisitAst[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.__Canon)
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitChildren(Antlr4.Runtime.Tree.IRuleNode)
   at Dax.Analyzer.Ast.Visitor.DaxVisitor.Visit(Antlr4.Runtime.Tree.IParseTree)
   at Dax.Analyzer.Ast.AstHelper.Parse(Microsoft.AnalysisServices.Tabular.Model, System.String, Dax.Analyzer.Ast.ExpressionType, Dax.Analyzer.IDependencyResolver, Microsoft.AnalysisServices.Tabular.Table, Dax.Analyzer.EvaluationContext, Boolean, Dax.Analyzer.Internal.DaxLocale, Dax.Analyzer.Ast.SemanticEngineFeatures)
   at Dax.Analyzer.SemanticAnalyzer.StrongType(System.String)
   at Dax.Analyzer.SemanticAnalyzer.FullSemanticAnalysisInternal(Boolean, Boolean)
   at Dax.Analyzer.SemanticAnalyzer.FullSemanticAnalysisWithEvents(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)


Thanks for your help. Tabular Editor is so powerfull that it's extremely problematic not to be able to use it anymore.
Best regards.
Marc
SAS Business And Project BI
120 avenue de Wagram
75017 Paris
+33 (0) 6 66 69 84 25
[Logo YouKey]

De : Daniel Otykier ***@***.***>
Envoyé : mardi 28 septembre 2021 15:57
À : TabularEditor/TabularEditor3 ***@***.***>
Cc : Marc LEMPEREUR ***@***.***>; Mention ***@***.***>
Objet : Re: [TabularEditor/TabularEditor3] impossible to open tabular editor from Power Bi Desktop (#229)


Hi @PalombieChamonix<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPalombieChamonix&data=04%7C01%7Cmarc%40youkey.fr%7C15972a2001ac472684c808d98287c8d5%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684341967773821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w8JtSHGFooovnD%2FglyxkqlW7NaaYb17eW0IRbMu1r6M%3D&reserved=0>
To help us identify this issue could you launch the Windows Event Viewer and look for any .NET Runtime Error events within Windows Logs > Application around the time where Tabular Editor 3 closes itself. Please share the details of any such errors (see screenshot below for reference):

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8976200%2F135101179-69d6692c-c55b-4ccb-82cb-34c3f30c4a23.png&data=04%7C01%7Cmarc%40youkey.fr%7C15972a2001ac472684c808d98287c8d5%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684341967773821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8wKHuiz8bmGFNtw9%2FsURw%2BF6IrEeFP5xhtaNBormZLc%3D&reserved=0>

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTabularEditor%2FTabularEditor3%2Fissues%2F229%23issuecomment-929245650&data=04%7C01%7Cmarc%40youkey.fr%7C15972a2001ac472684c808d98287c8d5%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684341967773821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=breUzbH%2FU9QE0d0YSCEFMmE37qzpz7CLgz092YOqZDU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVYJC73JKILEKRTNKL62UF3UEHCRDANCNFSM5E5PHD3A&data=04%7C01%7Cmarc%40youkey.fr%7C15972a2001ac472684c808d98287c8d5%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684341967783779%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GCwrL%2BZO7O5%2BXNJ%2F68zuU%2BIJN1Ip9rv7AnKN3wd70Rg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmarc%40youkey.fr%7C15972a2001ac472684c808d98287c8d5%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684341967783779%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z0SMEsSollx%2F159SVjycX9EJPnDrxarghjh4gwDx6iQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmarc%40youkey.fr%7C15972a2001ac472684c808d98287c8d5%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684341967793735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TrtKYex%2B9D33g1oxJemdBI1Gfc89slvgVMNnbnNbrfw%3D&reserved=0>.

**Comment by PalombieChamonix** [comment]
Version : 2.97.861.0 64-bit (septembre 2021)

Unfortunately, because of a SAL I cannot send you the file.

Regards.
Marc
SAS Business And Project BI
120 avenue de Wagram
75017 Paris
+33 (0) 6 66 69 84 25
[Logo YouKey]
De : Daniel Otykier ***@***.***>
Envoyé : mardi 28 septembre 2021 16:01
À : TabularEditor/TabularEditor3 ***@***.***>
Cc : Marc LEMPEREUR ***@***.***>; Mention ***@***.***>
Objet : Re: [TabularEditor/TabularEditor3] impossible to open tabular editor from Power Bi Desktop (#229)


Also, some additional questions:

  *   Which version of Power BI Desktop are you using?
  *   Does this happen for all pbix reports or only for some? Would it be possible for you to share one of the problematic .pbix or .pbit files with me (send to ***@***.******@***.***>)?

Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTabularEditor%2FTabularEditor3%2Fissues%2F229%23issuecomment-929252575&data=04%7C01%7Cmarc%40youkey.fr%7C3d63c971b7d84157df9708d982885ffa%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684344506330399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DI2Xr51Ed3B30RGYJVopQXo6dn1le9ofxpFGe0JvqXM%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVYJC7Y5LSXBTG6UQCN4W6DUEHDA7ANCNFSM5E5PHD3A&data=04%7C01%7Cmarc%40youkey.fr%7C3d63c971b7d84157df9708d982885ffa%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684344506330399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SLZll8TVeHUqBWzSmqIyWFVHMYFaYTLL09cLstNhh84%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmarc%40youkey.fr%7C3d63c971b7d84157df9708d982885ffa%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684344506340368%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=O8QKCyTIA5RuFwKbu3bnYQ6p4n7xYuZ0CmEa95W8OQk%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmarc%40youkey.fr%7C3d63c971b7d84157df9708d982885ffa%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637684344506340368%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kXhaXcRW9S3Y8Ebnan2CRlHEYOHWd9W8%2BNqzc5M%2FMRE%3D&reserved=0>.

**Comment by otykier** [comment]
Thanks a lot. The event details you provided are very valuable and I think we can identify the issue without having a file repro. Will update you later today.

**Comment by otykier** [comment]
This should now be fixed with version [3.1.1](http://localhost:8080/te3/other/release-notes/3_1_1.html). Thanks again for providing the error details!

**Comment by PalombieChamonix** [comment]
Thanks !!!!!!!!!!!!!!!!!
