### ISSUE TITLE
Unhandled error when copy-pasting a calculated column

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#35]
I wanted to create a very similar calculated column from an existing one so I copy-pasted it and then unhandled error message appeared. Restarting TE3 and doing the same produced the same error. 

Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.0.2 (3.0.7824.16345)
OS version: Microsoft Windows NT 10.0.19043.0
Model details: 
		CompatibilityLevel: 1550
	CompatibilityMode: PowerBI
	IsPbiDesktop: True
	SourceType: Database
	TableCount: 1
	FirstTimeModelLoad: False
	DatabaseNameSHA256: 51929e95bfe2dca109ecf5d09a42cdfbaabac1242e1f323b
	ServerVersion: 15.1.88.19
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: Enterprise64
	ServerNameSHA256: 4bd566fcfa28c6ecd9d0c30232139b646318df816186e83d
User description: 
Exception message: An object with lineage-tag 'd2ed44b6-db82-434f-b482-703c4ee4d16f' already exists in the collection.
Exception source: Microsoft.AnalysisServices.Tabular
Stack trace:    at Microsoft.AnalysisServices.Tabular.ColumnCollection.ValidateCanAdd(Column item)
   at Microsoft.AnalysisServices.Tabular.MetadataObjectCollection`2.Add(T metadataObject)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1.InternalAdd(T item)
   at TabularEditor.TOMWrapper.ColumnCollection.InternalAdd(Column item)
   at TabularEditor.TOMWrapper.CalculatedColumn.CreateFromMetadata(Table parent, CalculatedColumn metadataObject)
   at TabularEditor.TOMWrapper.TabularCommonActions.InsertObjects(ObjectJsonContainer objectContainer, ITabularNamedObject destination)
   at TabularEditor.UI.Services.EditService.Paste()
   at TabularEditor.UI.Utils.SimpleLink.Click(Object sender, EventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Modules loaded: 
		tabulareditor3.exe

**Comment by otykier** [comment]
Thanks for reporting. A fix will be available shortly.

**Comment by otykier** [comment]
Fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to reopen the ticket or create a new one if the issue persists.

**Comment by amrsharonng** [comment]
Hello, I am having the same issue when copying another table from a different data model: 

Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.3.2 (3.3.8214.28396)
OS version: Microsoft Windows NT 10.0.19044.0
Model details: 
		CompatibilityLevel: 1500
	CompatibilityMode: AnalysisServices
	IsPbiDesktop: False
	SourceType: Database
	TableCount: 187
	FirstTimeModelLoad: False
	DatabaseNameSHA256: a04f9190a1f7cb6407693e671189f07c8f010e4cf0e8909f
	ServerVersion: 15.0.35.15
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: EnterpriseCore64
	ServerNameSHA256: 133259c132e352db8f52f7ea55a0d1850df619ca2be36b61
User description: 
Exception message: Unrecognized JSON property: lineageTag. Check path 'lineageTag', line 1, position 37.
Exception source: Microsoft.AnalysisServices.Tabular
