### ISSUE TITLE
Tabular Editor (Latest Version) Crashes with the below report - any ideas?

### ISSUE THREAD

**Issue by thomachan101** [TabularEditor/TabularEditor3#358]
Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.2.0 (3.2.8055.2602)
OS version: Microsoft Windows NT 10.0.19042.0
Model details: 
		CompatibilityLevel: 1550
	CompatibilityMode: PowerBI
	IsPbiDesktop: True
	SourceType: Database
	TableCount: 8
	FirstTimeModelLoad: False
	DatabaseNameSHA256: 5cc56ede1109a5a2828842b1b0056050e068385785dec792
	ServerVersion: 16.0.5.24
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: Enterprise64
	ServerNameSHA256: da8563f7089cfff7240bc7976fe6a571cdb042bd0c8fff72
User description: 
Exception message: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
Exception source: System.Windows.Forms
Stack trace:    at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at TabularEditor.UI.ViewModels.TabularExplorerData.TreeListFullRefresh()
   at TabularEditor.UI.Views.TabularExplorerView.ModelManagerService_SemanticAnalysisCompleted(Object sender, SemanticAnalysisCompletedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
Modules loaded: 
		tabulareditor3.exe

**Comment by thomachan101** [comment]
Seems it is same issue as #357
