### ISSUE TITLE
Crash when clicking on DataRefresh Info

### ISSUE THREAD

**Issue by lukiz84** [TabularEditor/TabularEditor3#370]
**TabularEditor 3.20**

Hi,
when I start data refresh and want to go to the details by clicking the Link in the **Status bar** the following exception is thrown:

Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.2.0 (3.2.8055.2602)
OS version: Microsoft Windows NT 10.0.18363.0
Model details: 
		CompatibilityLevel: 1500
	CompatibilityMode: AnalysisServices
	IsPbiDesktop: False
	SourceType: Database
	TableCount: 123
	FirstTimeModelLoad: False
	DatabaseNameSHA256: 7c30f912273c190658376053c7510990a3146c7fe67d53fd
	ServerVersion: 15.0.35.9
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: EnterpriseCore64
	ServerNameSHA256: 295a8c4c78eaa3841fde33f390911b41eaf3c56008e5861b
User description: 
Exception message: Sequence contains no elements
Exception source: System.Core
Stack trace:    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at TabularEditor.UI.Services.ViewServiceExtensions.GoToModelProcessing(IViewService viewService)
   at TabularEditor.Main.StatusText_HyperlinkClick(Object sender, HyperlinkClickEventArgs e)
   at DevExpress.XtraBars.BarItem.OnHyperLinkClick(BarItemLink link, StringBlock hyperlink, MouseEventArgs mouseArgs)
   at DevExpress.XtraBars.Controls.CustomLinksControl.CheckNavigateHyperlink(BarItemLink link, MouseEventArgs mouseArgs)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at DevExpress.XtraBars.Controls.DockedBarControl.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Modules loaded: 
		TabularEditor3.exe

BR
Lukas

**Comment by otykier** [comment]
Thanks for reporting.

A workaround until we get this fixed, is to manually navigating to the Data Refresh tab at once (i.e. by going to the **View > Data Refresh** menu option), before clicking on the link in the status bar.

**Comment by otykier** [comment]
Fixed in [3.2.2](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.2), thanks for reporting.
