### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor3#40]
Hi, when I was trying to save I got a warning saying that there were some changes outside TE3 and that if I proceed it will merge everything. I did that before and takes a long time, so what I did was copy the text of the calculated table I was about to create and clicked the Refresh metadata button to reset it to whatever TE3 thinks is the current state of PBID model. 
Then the error appeared. 

Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.0.2 (3.0.7824.16345)
OS version: Microsoft Windows NT 10.0.19043.0
Model details: 
		CompatibilityLevel: 1550
	CompatibilityMode: PowerBI
	IsPbiDesktop: True
	SourceType: Database
	TableCount: 13
	FirstTimeModelLoad: False
	DatabaseNameSHA256: 8d427436d07e039e3787d526ea7047082414cf1194c55a32
	ServerVersion: 15.1.88.19
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: Enterprise64
	ServerNameSHA256: d0056963709c50bf170c3e869fad691e47ffb448d608d3e2
User description: 
Exception message: Object reference not set to an instance of an object.
Exception source: System.Windows.Forms
Stack trace:    at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at TabularEditor.UI.ViewModels.TabularExplorerData.EndUpdate()
   at TabularEditor.TOMWrapper.TabularModelHandler.RefreshTom()
   at TabularEditor.UI.Utils.SimpleLink.Click(Object sender, EventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at DevExpress.XtraBars.Controls.DockedBarControl.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Modules loaded: 
		tabulareditor3.exe

**Comment by otykier** [comment]
Fixed in [3.0.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.3). Please feel free to reopen the ticket or create a new one if the issue persists.
