### ISSUE TITLE
Cannot import ODBC Snowflake

### ISSUE THREAD

**Issue by jiskim** [TabularEditor/TabularEditor3#448]
When trying to import any tables from an odbc connecting to snowflake that was working in Visual Studio, i get the following error.

![image](https://user-images.githubusercontent.com/1792543/156015851-5cb4df24-f903-4a4e-82a5-35c7663e96d3.png)

i was using power Query mode, if i back from the previous error and i do it in Legacy instead mode i get the following error.

`Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.2.2 (3.2.8083.15566)
OS version: Microsoft Windows NT 10.0.17763.0
Model details: 
		CompatibilityLevel: 1500
	CompatibilityMode: AnalysisServices
	IsPbiDesktop: False
	SourceType: Database
	TableCount: 0
	FirstTimeModelLoad: False
	DatabaseNameSHA256: 17ece5f14442753c3d12aaf263cc0555f9ab9f1f89e0ba35
	ServerVersion: 15.0.32.50
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: Developer64
	ServerNameSHA256: e46efcfddf2ef3d48349b2dada9be3672febaf875c8418ca
User description: 
Exception message: Property 'ConnectionDetails' contains invalid JSON. Error: Error reading JObject from JsonReader. Path '', line 0, position 0.. Check path '', line 0, position 0.
Exception source: Microsoft.AnalysisServices.Tabular
Stack trace:    at Microsoft.AnalysisServices.Tabular.JsonPropertyHelper.ConvertStringToJsonObject(String rawString, String propName)
   at Microsoft.AnalysisServices.Tabular.StructuredDataSource.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeObjectImpl(MetadataObject metadataObject, SerializeOptions options, Int32 dbCompatibilityLevel, CompatibilityMode mode)
   at TabularEditor.TOMWrapper.Undo.UndoAddRemoveAction..ctor(ITabularObjectCollection collection, TabularNamedObject obj, UndoAddRemoveActionType actionType)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1.InternalRemove(T item)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1.TabularEditor.TOMWrapper.ITabularObjectCollection.Remove(TabularNamedObject item)
   at TabularEditor.TOMWrapper.TabularNamedObject.InternalDelete()
   at TabularEditor.TOMWrapper.TabularNamedObject.Delete()
   at TabularEditor.TOMWrapper.Undo.UndoManager.XDo(Boolean redo, Boolean inversable)
   at TabularEditor.TOMWrapper.Undo.UndoManager.EndBatch(Boolean rollback)
   at TabularEditor.TOMWrapper.TabularModelHandler.EndUpdateAll(Boolean rollback)
   at TabularEditor.UI.Services.TableImportWizardService.CreateNewSource(VirtualDataSourceType virtualDataSourceType, ServerType connectionMode, ImpersonationType impersonationType, String dataSourceName)
   at TabularEditor.UI.Dialogs.ImportTableWizard.WizardControl1_SelectedPageChanging(Object sender, WizardPageChangingEventArgs e)
   at DevExpress.XtraWizard.WizardControl.RaiseSelectedPageChanging(BaseWizardPage oldPage, BaseWizardPage newPage, Direction direction)
   at DevExpress.XtraWizard.WizardControl.SetSelectedPageCore(BaseWizardPage prevPage, BaseWizardPage value, Direction direction)
   at DevExpress.XtraWizard.WizardControl.SetNextPage()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.BaseWndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Modules loaded: 
		TabularEditor3.exe`

if i exit the app AND do it in legacy i get 

![image](https://user-images.githubusercontent.com/1792543/156016418-6359d1a6-e7f3-454e-bdae-edb2b8441a20.png)

again

i tried in both a new project and in an existing bim file. 

here is my dsn config.

![image](https://user-images.githubusercontent.com/1792543/156017097-5166db73-fece-4653-aa9d-9122c00c8944.png)

and here is the page for the driver doc. 

https://docs.snowflake.com/en/user-guide/odbc.html

Hopefully this is on my end.

Thanks!

**Comment by otykier** [comment]
Thanks for the detailed error description. We will look into it.

**Comment by cosminioan** [comment]
have the same issue. using TE 3.2.8132.  Would love to be able to use TE with Snowflake.
thank you kindly for looking into it.  (I have sent a support email also, a few mins ago.)

**Comment by otykier** [comment]
This is now fixed in [3.3.4](https://docs.tabulareditor.com/te3/other/release-notes/3_3_4.html). Thanks for the detailed information provided.
