### ISSUE TITLE
TE3 crashes immediately upon launch

### ISSUE THREAD

**Issue by Stewwe1** [TabularEditor/TabularEditor3#455]
Hello Daniel,

I installed the latest version and immediately get an error message:

![image](https://user-images.githubusercontent.com/49725984/157012762-beac56d4-c3e0-4483-9d7d-5ff7ac917599.png)

Thank you for your help!

Steffen

**Comment by otykier** [comment]
Hi Steffen,
Could you please share the detailed error report here ("View error report...")

The usual workaround for issues upon launch of the tool is to delete or rename the `%localappdata%\TabularEditor3\Layout.json` file. Could you try that and let us know the result? Thanks!

**Comment by Stewwe1** [comment]
Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.2.2 (3.2.8083.15566)
OS version: Microsoft Windows NT 10.0.19043.0
Model details: 
	(No model loaded)
User description: 
Exception message: Object reference not set to an instance of an object.
Exception source: TabularEditor3
Stack trace:    at TabularEditor.UI.Views.ModelProcessingView.InitView()
   at TabularEditor.UI.Views.BaseUIView.InitializeView()
   at DevExpress.XtraEditors.XtraUserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at TabularEditor.UI.Utils.CustomWorkspaceManager.LoadContentVisiblePanels(DockPanel panel)
   at TabularEditor.UI.Utils.CustomWorkspaceManager.LoadContentVisiblePanels(DockPanel panel)
   at TabularEditor.UI.Utils.CustomWorkspaceManager.LoadContentVisiblePanels()
   at TabularEditor.UI.Utils.CustomWorkspaceManager.ApplyLayout(SerializableLayout layout)
   at TabularEditor.UI.Utils.WorkspaceService.Init(XtraForm main, CustomWorkspaceManager manager, BarManager barManager)
   at TabularEditor.Main.Main_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Modules loaded: 
		TabularEditor3.exe

**Comment by Stewwe1** [comment]
When I delete the Layout.json it works :-)

Thanks

**Comment by jeppelykkebjerg** [comment]
I get this error too :-) 

If I choose "ignore", and proceed TE3 doesn't work properly. Now I only have the possiblity to load model from a Power BI instance.

![image](https://user-images.githubusercontent.com/78149077/157208045-5bcf71dc-dec0-4f56-be21-e12e9880f215.png)

**Comment by otykier** [comment]
Hi @jeppelykkebjerg 
This looks like a different issue. Which edition of Tabular Editor 3 did you purchase?

**Comment by jeppelykkebjerg** [comment]
Hi Daniel,

This is the Enterprise edition.

**Comment by otykier** [comment]
I see. Did you try the workaround mentioned above?

**Comment by jeppelykkebjerg** [comment]
Just did it - it works. 

Though, the app layout from my prior version was deleted (makes sense). I noticed that when i re-ordered my layout, closed the application and started it up again, the same error appeared. Thus, I had to the deletion of the layout.json once again.

**Comment by otykier** [comment]
Could you let us know which type of layout change you made, that caused the issue upon next launch? (Or alternatively, share the faulty Layout.json file which causes the crash) Thanks!

**Comment by jeppelykkebjerg** [comment]
Sure!
[Layouts.zip](https://github.com/TabularEditor/TabularEditor3/files/8205004/Layouts.zip)

**Comment by otykier** [comment]
This issue has now been fixed in [3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3). Thanks everyone, for your patience while we worked on this.
