### ISSUE TITLE
TA3 crash when launched

### ISSUE THREAD

**Issue by koltachin** [TabularEditor/TabularEditor3#503]
Very disappointing  since more than a month the TE3 fails to open 
here the message I get every single start
why paying for a tools that does not work properly
 
Roger

Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.2.2 (3.2.8083.15566)
OS version: Microsoft Windows NT 10.0.19044.0
Model details: 
	(No model loaded)
User description: 
Exception message: Object reference not set to an instance of an object.
Exception source: TabularEditor3
Stack trace:    at TabularEditor.UI.Views.ModelProcessingView.InitView()
   at TabularEditor.UI.Views.BaseUIView.InitializeView()
   at DevExpress.XtraEditors.XtraUserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at TabularEditor.UI.Utils.CustomWorkspaceManager.LoadContentVisiblePanels(DockPanel panel)
   at TabularEditor.UI.Utils.CustomWorkspaceManager.LoadContentVisiblePanels()
   at TabularEditor.UI.Utils.CustomWorkspaceManager.ApplyLayout(SerializableLayout layout)
   at TabularEditor.UI.Utils.WorkspaceService.Init(XtraForm main, CustomWorkspaceManager manager, BarManager barManager)
   at TabularEditor.Main.Main_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Modules loaded: 
		tabulareditor3.exe

**Comment by otykier** [comment]
Sorry to hear that you’re disappointed with the tool. I wish you’d reached out the first time you encountered the issue instead of a month later…

This issue was reported a while ago and a workaround has been [posted here](https://github.com/TabularEditor/TabularEditor3/issues/455#issuecomment-1060454029). It was also fixed in [v. 3.2.3](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.2.3) which was released a few days ago.

**Comment by otykier** [comment]
Also, please contact sales@tabulareditor.com and refer them to this ticket to get a refund for the period you couldn’t use the tool.
