### ISSUE TITLE
Error when launching TE from PowerBI

### ISSUE THREAD

**Issue by PalombieChamonix** [TabularEditor/TabularEditor3#571]
Since the last version, nearly all our attemps to use TE from PowerBI fail :

 
![image](https://user-images.githubusercontent.com/91263359/174658505-2e217d51-449e-4728-b4e6-afd2439aeea6.png)

**Comment by PalombieChamonix** [comment]
Indeed...impossible du to NDA.
Our test with 4 different datasets are facing the same issue.

**Comment by otykier** [comment]
That’s why I suggested a pbit rather than a pbix, since a pbit does not contain any data. 

Unfortunately, we have not seen this issue in our internal testing, so we will need some more information in order to investigate further. It would be helpful if you could narrow it down for us. Does all your models cause this issue, or do some of them still work? You might also get a clue to what’s going on by stripping down one of the models that doesn’t work little by little until the issue no longer occurs, taking note on what change you made that caused the issue to disappear.

Any additional info you can provide would be very helpful.

**Comment by otykier** [comment]
@PalombieChamonix it would be helpful if you can try to run the following script in Tabular Editor 3 and share the output:

```csharp
// TODO: Set Power BI Desktop port number:
int portNumber = 56150;

try
{
    new TabularModelHandler($"localhost:{portNumber}", databaseName: null);
    Info("Successfully created model handler object");
}
catch(Exception ex)
{
    ex.Output();
}
```

Please set the `portNumber` variable to the port number of the Power BI Desktop instance that holds your model. You should be able to see the port number in the "Local instance" dropdown in the "Load Model from Database" dialog (Ctrl+Shift+O).

![image](https://user-images.githubusercontent.com/8976200/174799674-b3291746-d04f-414a-aa6b-c8a5ff686771.png)

Thank you!

**Comment by PalombieChamonix** [comment]
Thanks for your help. Here is the result : 
![image](https://user-images.githubusercontent.com/91263359/174824193-64c25905-b697-4b77-85de-28740dbf4b6c.png)

**Comment by otykier** [comment]
@PalombieChamonix still looking into this. Just to clarify: Are you opening a model from Power BI Desktop or from the Power BI XMLA endpoint?

**Comment by PalombieChamonix** [comment]
I've just made a new test with the same script. I'm openin a model from PowerBI Desktop :
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabularEditor.TOMWrapper.CalculationGroupTable.get_CalculationItems()
   at TabularEditor.TOMWrapper.CalculationGroupTable.get_ChildErrorCount()
   at TabularEditor.TOMWrapper.Table.AddError()
   at TabularEditor.TOMWrapper.Measure.Init()
   at TabularEditor.TOMWrapper.Measure.CreateFromMetadata(Table parent, Measure metadataObject)
   at TabularEditor.TOMWrapper.MeasureCollection.CreateFromMetadata(Measure obj)
   at TabularEditor.TOMWrapper.MeasureCollection.CreateChildrenFromMetadata()
   at TabularEditor.TOMWrapper.Table..ctor(Table metadataObject, TabularModelHandler handler)
   at TabularEditor.TOMWrapper.CalculationGroupTable..ctor(Table table, TabularModelHandler handler)
   at TabularEditor.TOMWrapper.CalculationGroupTable.CreateFromMetadata(Model parent, Table metadataObject)
   at TabularEditor.TOMWrapper.TableCollection.CreateFromMetadata(Table obj)
   at TabularEditor.TOMWrapper.TableCollection.CreateChildrenFromMetadata()
   at TabularEditor.TOMWrapper.Model..ctor(Model metadataObject, TabularModelHandler handler)
   at TabularEditor.TOMWrapper.Model.CreateFromMetadata(Model metadataObject, TabularModelHandler handler)
   at TabularEditor.TOMWrapper.TabularModelHandler.InternalInit()
   at TabularEditor.TOMWrapper.TabularModelHandler..ctor(String serverNameOrConnectionString, String databaseName, TabularModelHandlerSettings settings)
   at Submission#0.<<Initialize>>d__0.MoveNext() in :line 5

**Comment by otykier** [comment]
Fixed in [3.3.1](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.3.1). Thanks for reporting!

**Comment by PalombieChamonix** [comment]
Sorry, for the bug is not fixed with the new release.
This time, TE fails at the very beginning :
***@***.***

De : Daniel Otykier ***@***.***>
Envoyé : lundi 27 juin 2022 19:10
À : TabularEditor/TabularEditor3 ***@***.***>
Cc : Marc LEMPEREUR ***@***.***>; Mention ***@***.***>
Objet : Re: [TabularEditor/TabularEditor3] Error when launching TE from PowerBI (Issue #571)


Fixed in 3.3.1<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTabularEditor%2FTabularEditor3%2Freleases%2Ftag%2F3.3.1&data=05%7C01%7Cmarc%40youkey.fr%7C9243f1c1f2d24b82e97308da585fd928%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637919465935294817%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BpyDoI2652bSFAcGE0QlnGqmdZwQjDL1ViifPx%2FruNs%3D&reserved=0>. Thanks for reporting!

-

**Comment by otykier** [comment]
Could you share the contents of “View error report…” too, please?

**Comment by PalombieChamonix** [comment]
I tried to get the view error report but something happens…then TE shuts down. Can I get further information about this bug ?

YouKey
________________________________
De : Daniel Otykier ***@***.***>
Envoyé : Tuesday, June 28, 2022 2:17:36 AM
À : TabularEditor/TabularEditor3 ***@***.***>
Cc : Marc LEMPEREUR ***@***.***>; Mention ***@***.***>
Objet : Re: [TabularEditor/TabularEditor3] Error when launching TE from PowerBI (Issue #571)


Could you share the contents of “View error report…” too, please?

**Comment by otykier** [comment]
Could you take a look in the Windows Event Viewer? Under Windows Logs > Application, look for any .NET Runtime error around the time of the crash, as shown below:

![097F4331-108E-42C9-991C-FF5ECD9C092E](https://user-images.githubusercontent.com/8976200/176064929-c4a5b604-6677-429e-a10d-69d446aa03ee.png)

**Comment by otykier** [comment]
Issue might be related to telemetry. Please try to disable [Help improve Tabular Editor by collecting anonymous usage data](https://docs.tabulareditor.com/te3/features/preferences.html#tabular-editor--updated-and-feedback)

**Comment by PalombieChamonix** [comment]
We unselected this option : ko

***@***.***
Marc
+33 (0) 6 66 69 84 25
SAS Business And Project BI
120 avenue de Wagram
75017 Paris
https://youkey.fr<https://youkey.fr/>


De : Daniel Otykier ***@***.***>
Envoyé : mardi 28 juin 2022 03:22
À : TabularEditor/TabularEditor3 ***@***.***>
Cc : Marc LEMPEREUR ***@***.***>; Mention ***@***.***>
Objet : Re: [TabularEditor/TabularEditor3] Error when launching TE from PowerBI (Issue #571)


Issue might be related to telemetry. Please try to disable Help improve Tabular Editor by collecting anonymous usage data<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.tabulareditor.com%2Fte3%2Ffeatures%2Fpreferences.html%23tabular-editor--updated-and-feedback&data=05%7C01%7Cmarc%40youkey.fr%7Cd99f30ca83754b0b44a508da58a489ee%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637919760957556577%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=07oUlEN95BdLoBXoDz7eVZ%2FxZn79i1Sodqrydj7dFoM%3D&reserved=0>

-

**Comment by PalombieChamonix** [comment]
These are the error messages :
Application: tabulareditor3.exe
CoreCLR Version: 6.0.622.26707
.NET Version: 6.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'TabularEditor.Shared.Services.SensitiveProcessor' threw an exception.
---> System.MissingMethodException: Method not found: 'Void TabularEditor.Utils.TrieReplaceOptions.set_StripPiiLabels(Boolean)'.
at TabularEditor.Shared.Services.SensitiveProcessor..cctor()
--- End of inner exception stack trace ---
at TabularEditor.Shared.Services.SensitiveProcessor.StripSensitive(String original)
at TabularEditor.UI.Dialogs.ErrorReportDialog.GetErrorReport(Exception exception, String userMessage)
at TabularEditor.Program.Application_ThreadException(Object sender, ThreadExceptionEventArgs e)
at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
at DevExpress.Utils.Drawing.Helpers.NativeMethods.UnsafeNativeMethods.DefSubclassProc(IntPtr hWnd, IntPtr Msg, IntPtr wParam, IntPtr lParam)
at DevExpress.Utils.Drawing.Helpers.NativeMethods.DefSubclassProc(IntPtr hWnd, IntPtr Msg, IntPtr wParam, IntPtr lParam)
at DevExpress.Utils.Drawing.Helpers.Win32SubclasserFactory.Win32Subclasser.SubClassProcInner(IntPtr hWnd, IntPtr Msg, IntPtr wParam, IntPtr lParam, IntPtr uIdSubclass, IntPtr dwRefData)
at Interop.User32.DispatchMessageW(MSG& msg)
at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(Form mainForm)
   at TabularEditor.Program.Main()


Nom de l'application défaillante tabulareditor3.exe, version : 3.3.8213.26564, horodatage : 0x6283e0e1
Nom du module défaillant : KERNELBASE.dll, version : 10.0.22000.778, horodatage : 0x5f5438c2
Code d'exception : 0xe0434352
Décalage d'erreur : 0x000000000004474c
ID du processus défaillant : 0x7160
Heure de début de l'application défaillante : 0x01d88ab4e49ad309
Chemin d'accès de l'application défaillante : C:\Program Files\Tabular Editor 3\tabulareditor3.exe
Chemin d'accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : 3f411e9f-9111-488d-99b4-065b83375eb5
Nom complet du package défaillant :
ID de l'application relative au package défaillant :

***@***.***
Marc
+33 (0) 6 66 69 84 25
SAS Business And Project BI
120 avenue de Wagram
75017 Paris
https://youkey.fr<https://youkey.fr/>


De : Daniel Otykier ***@***.***>
Envoyé : mardi 28 juin 2022 03:06
À : TabularEditor/TabularEditor3 ***@***.***>
Cc : Marc LEMPEREUR ***@***.***>; Mention ***@***.***>
Objet : Re: [TabularEditor/TabularEditor3] Error when launching TE from PowerBI (Issue #571)


Could you take a look in the Windows Event Viewer? Under Windows Logs > Application, look for any .NET Runtime error around the time of the crash, as shown below:

[097F4331-108E-42C9-991C-FF5ECD9C092E]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8976200%2F176064929-c4a5b604-6677-429e-a10d-69d446aa03ee.png&data=05%7C01%7Cmarc%40youkey.fr%7Cafc620e2e9094943720208da58a264d2%7C1ddf80fd35ab40ab994826984cd2818e%7C0%7C0%7C637919751741237382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O0t22cm8baG4lJo5U6Nhzy0f61MmGQUTVjh%2FvonFQP8%3D&reserved=0>

-

**Comment by otykier** [comment]
Thanks for the detailed reply. Indeed, this is the same issue as #586 - continuing the discussion there.
