### ISSUE TITLE
Preview data results in an error /  crash

### ISSUE THREAD

**Issue by kjoebie** [TabularEditor/TabularEditor3#726]
After connecting to a model on AAS I select a table and select Preview Data. The data is loaded and when I choose the Last option... 

![image](https://user-images.githubusercontent.com/7207207/204797599-4a74d5a3-58df-41b6-8931-674418ee29e0.png)

... then TE crashes with the following error:
Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.3.6 (3.3.8350.24632)
OS version: Microsoft Windows NT 10.0.19045.0
Model details: 
		CompatibilityLevel: 1500
	CompatibilityMode: AnalysisServices
	IsPbiDesktop: False
	SourceType: Database
	TableCount: 5
	FirstTimeModelLoad: False
	DatabaseNameSHA256: b5d77bb98bcbd0b8dafd6da7cda46b73a5c3379f6d58e6cd
	ServerVersion: 16.0.51.25
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: Enterprise64
	ServerNameSHA256: dff70db62efdd2897ff1810283cbde4c71817c4841e6ba23
User description: 
Exception message: Object reference not set to an instance of an object.
Exception source: TabularEditor3
Stack trace:    at TabularEditor.UI.DxExtensions.DataRowPropertyDescriptor.GetValue(Object component)
   at DevExpress.XtraGrid.Views.Grid.GridView.GetRowCellValue(Int32 rowHandle, GridColumn column, OperationCompleted completed)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.UpdateRowCellValue(GridDataRowInfo ri, GridCellInfo cell, RowDataDirtyKind flag)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.UpdateRowCells(GridDataRowInfo ri, RowDataDirtyKind flag, Boolean resetChangedCells)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.UpdateRowDataCore(GridRowInfo bi, Boolean updateMouse, RowDataDirtyKind flag, Boolean resetChangedCells)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CheckRowData(GridRowInfo ri, Boolean resetChangedCells)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.UpdateBeforePaint(GridRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRow(GridViewDrawArgs e, GridRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRows(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawContentsCore(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawCore(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.Draw(ViewDrawArgs ee)
   at DevExpress.XtraGrid.Views.Base.BaseView.Draw(GraphicsCache e)
   at DevExpress.XtraGrid.Views.Grid.GridView.Draw(GraphicsCache e)
   at DevExpress.XtraGrid.GridControl.OnPaintCore(PaintEventArgs e)
   at DevExpress.Utils.DirectXPaint.DirectXProvider.RenderCore(Rectangle clipRect, Boolean setDirtyRect, Graphics g)
   at DevExpress.Utils.DirectXPaint.DirectXProvider.RenderDirtyRects(Graphics g)
   at DevExpress.Utils.DirectXPaint.DirectXPaint.ProcessWmPaint(Message m)
   at DevExpress.Utils.DirectXPaint.DirectXProvider.BeforeWndProc(Message& m)
   at DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
Modules loaded: 
		TabularEditor3.dll

Choosing abort will stop TE working.

**Comment by otykier** [comment]
Thanks for reporting!

**Comment by otykier** [comment]
This is now fixed in [3.4.0](https://docs.tabulareditor.com/te3/other/release-notes/3_4_0.html). Thanks for reporting!
