### ISSUE TITLE
Reopen: Copy paste cultures from one TE session into another #507

### ISSUE THREAD

**Issue by MarioMue13** [TabularEditor/TabularEditor3#798]
I just try to copy paste a culture from an existing model into a completly new one:

Copy paste cultures from one TE session into another #507 .

Error Report:

Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.4.0 (3.4.8392.26581)
OS version: Microsoft Windows NT 10.0.19045.0
Model details: 
		CompatibilityLevel: 1500
	CompatibilityMode: AnalysisServices
	IsPbiDesktop: False
	SourceType: UnsavedFile
	TableCount: 0
	FirstTimeModelLoad: True
	DatabaseNameSHA256: e6e1e239581ee92f20346b17d4d6d1f1fc636ab2d4292ae3
User description: 
Exception message: Object reference not set to an instance of an object.
Exception source: Microsoft.AnalysisServices.Tabular
Stack trace:    at Microsoft.AnalysisServices.Tabular.Utils.SerializeSparseCollection(IEnumerable`1 sparseCollection, SparseSerializerSettings settings)
   at Microsoft.AnalysisServices.Tabular.ObjectTranslationCollection.SerializeToJsonObject()
   at Microsoft.AnalysisServices.Tabular.Culture.SerializeAdditionalDataToJsonObject(JsonObject jsonObj, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Culture.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.MetadataObject.SerializeToNewJsonObject(SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeObjectImpl(MetadataObject metadataObject, SerializeOptions options, Int32 dbCompatibilityLevel, CompatibilityMode mode)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeObject(MetadataObject metadataObject, SerializeOptions options)
   at TabularEditor.TOMWrapper.Undo.UndoAddRemoveAction..ctor(ITabularObjectCollection collection, TabularNamedObject obj, UndoAddRemoveActionType actionType)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1.InternalAdd(T item)
   at TabularEditor.TOMWrapper.TabularObjectCollection`1.Add(T item)
   at TabularEditor.TOMWrapper.Culture.CreateFromMetadata(Model parent, Culture metadataObject)
   at TabularEditor.TOMWrapper.Serialization.Serializer.DeserializeCulture(JObject json, Model model)
   at TabularEditor.TOMWrapper.TabularCommonActions.InsertObjects(ObjectJsonContainer objectContainer, Func`5 questionCallback, ITabularNamedObject destination, IInsertOptions insertOptions)
   at TabularEditor.UI.Services.EditService.Paste()
   at TabularEditor.UI.Utils.SimpleLink.ExecuteLink()
   at TabularEditor.UI.Utils.SimpleLink.Click(Object sender, EventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarBaseButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.OnShortcutItemClick(BarItem item, BarShortcut shortcut)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.CheckShortcut(BarManager manager, KeyEventArgs e)
   at DevExpress.XtraBars.MessageFilter.BarManagerHook.PreFilterMessage(Message& m)
   at DevExpress.XtraBars.MessageFilter.BarManagerMessageFilter.System.Windows.Forms.IMessageFilter.PreFilterMessage(Message& m)
Modules loaded: 
		TabularEditor3.dll

**Comment by mlonsk** [comment]
Hi @MarioMue13 
Thank you so much for reporting it in again, we will look into fixing it.
