### ISSUE TITLE
Debuging measure including PERCENTILEX.INC fails

### ISSUE THREAD

**Issue by HenrikHulstroem** [TabularEditor/TabularEditor3#971]
**Describe the issue**
Debuging measure including PERCENTILEX.INC fails.

** Which version are you currently using? **
![image](https://github.com/TabularEditor/TabularEditor3/assets/86058520/ff771274-ec00-41aa-baca-b5e68e881ca8)

**To Reproduce**
Connected to SSAS

Trying to debug value in pivot grid fails - see screenshots
Measure is: PERCENTILEX.INC ( V_TEST_RESULT2, V_TEST_RESULT2[TestResultActualRunTime], .25 )

**Expected behavior**
Being able to debug.

**Screenshots**
![image](https://github.com/TabularEditor/TabularEditor3/assets/86058520/a6f4ed80-2674-45d1-a5cf-f03909f04874)
![image](https://github.com/TabularEditor/TabularEditor3/assets/86058520/22834cd4-d33b-44a2-83f5-646c6153b0ef)

**Desktop (please complete the following information):**
Microsoft Windows 10 Enterprise 64-bit

**Additional context**
Error stacktrace is:
Tabular Editor Unhandled Exception Error Report
===============================================
Tabular Editor version: 3.9.0 (3.9.0.2972)
OS version: Microsoft Windows NT 10.0.19045.0
Model details: 
		CompatibilityLevel: 1400
	CompatibilityMode: AnalysisServices
	IsPbiDesktop: False
	SourceType: Database
	TableCount: 77
	FirstTimeModelLoad: False
	DatabaseNameSHA256: 5f1183338316b3a574fc7049dd0466b2b74a16c16f7ea636
	ServerVersion: 14.0.249.106
	ServerLocation: OnPremise
	ServerProductLevel: RTM
	ServerProductName: Microsoft SQL Server Analysis Services
	ServerEdition: EnterpriseCore64
	ServerNameSHA256: e52131e3c741da2dbe8d3e2c72498f7ae9524325a3e6156c
User description: 
Exception message: Object reference not set to an instance of an object.
Exception source: Daxscilla.Shared
Stack trace:    at DaxscillaEditor.TokenHelpers.GetTokenName(Int32 daxToken)
   at DaxscillaEditor.TokenHelpers.GetTokenName(Int32 daxToken, CasingStyle casingStyle)
   at DaxscillaEditor.TokenHelpers.GetTokenName(Int32 daxToken, ICasingSettings casingSettings, Boolean useKeywordCasing)
   at DaxscillaEditor.Utilities.TokenExtensions.GetDax(IToken token, IAutoFormatSettings autoFormatSettings, Nullable`1 isKeyword, Nullable`1 isFunction)
   at DaxscillaEditor.Utilities.TokenExtensions.GetDax(IEnumerable`1 tokens, IAutoFormatSettings autoFormatSettings)
   at DaxscillaEditor.Utilities.TokenExtensions.GetDax(IReadOnlyList`1 tokens, DaxBaseNode node)
   at Dax.Debugger.CallTreeFactory.GetDax(DaxBaseNode node)
   at Dax.Debugger.CallTreeFactory.GetCallTreeName(DaxBaseNode daxNode, Int32 maxLength)
   at Dax.Debugger.CallTreeFactory.CreateFunctionNode(DaxBaseNode daxNode, NodeConfig config)
   at Dax.Debugger.CallTreeFactory.CreateNode(DaxBaseNode daxNode, NodeConfig config)
   at Dax.Debugger.CallTreeFactory.CreateCallTreeFromMeasure(DdlObjectNode measureDdlNode, DaxInfo cache, Boolean flattenOperators)
   at Dax.Debugger.DebugSession.Reset(DebugSessionInitInfo initInfo)
   at TabularEditor.UI.Services.Debugging.DebugService.InitDebugSession(DebugSessionInitInfo initInfo)
   at TabularEditor.UI.Services.Debugging.DebugService.Start(DebugEntryPoint entryPoint)
   at TabularEditor.UI.Views.PivotGridView.DebugValue(PivotGridHitInfo hitInfo)
   at TabularEditor.UI.Views.PivotGridView.<>c__DisplayClass33_0.<PivotGrid_PopupMenuShowing>b__3(Object s, EventArgs e4)
   at DevExpress.Utils.Menu.DXMenuItem.OnClick()
   at DevExpress.Utils.Menu.DXMenuItem.GenerateClickEvent()
   at DevExpress.XtraBars.Utils.DXPopupXtraMenu.OnBarMenuClick(Object sender, ItemClickEventArgs e)
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarBaseButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   at DevExpress.XtraBars.Controls.CustomPopupBarControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraControl.WndProc(Message& m)
   at DevExpress.XtraBars.Controls.CustomControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
Modules loaded: 
		TabularEditor3.dll

**Comment by mlonsk** [comment]
Hi @HenrikHulstroem 

Thank you for reporting, definitely looks like a bug. We will investigate and look for a fix.

**Comment by otykier** [comment]
Fixed in [3.11.0](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.11.0). Thanks for reporting!
